myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.PostIndex.as_view(), name='index'),
    path('categoria/<str:categoria>', views.PostCategoria.as_view(), name='post_categorias'),
    path('busca/', views.PostBusca.as_view(), name='post_busca'),
    path('post/<int:pk>', views.PostDetalhes.as_view(), name='post_detalhes'),
]

categorias/models.py
from django.db import models

class Categoria(models.Model):
    nome_cat = models.CharField(max_length=50, verbose_name='Nome da Categoria')


    def __str__(self):
        return self.nome_cat

comentarios/models.py
from django.db import models
from posts.models import Post
from django.contrib.auth.models import User
from django.utils import timezone

class Comentario(models.Model):
    nome_comentario = models.CharField(max_length=150)
    email_comentario = models.EmailField()
    comentario = models.TextField()
    post_comentario = models.ForeignKey(Post, on_delete=models.CASCADE)
    usuario_comentario = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    data_comentario = models.DateTimeField(default=timezone.now)
    publicado_comentario = models.BooleanField(default=False)


    def __str__(self):
        return self.nome_comentario

posts/models.py
from distutils.command.upload import upload
from django.db import models
from categorias.models import Categoria
from django.contrib.auth.models import User
from django.utils import timezone


class Post(models.Model):
    titulo_post = models.CharField(max_length=255, verbose_name='Título')
    autor_post = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name='Autor')
    data_post = models.DateTimeField(default=timezone.now, verbose_name='Data')
    conteudo_post = models.TextField(verbose_name='Conteúdo')
    excerto_post = models.TextField(verbose_name='Excerto')
    categoria_post = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING, blank=True, null=True, verbose_name='Categoria')
    imagem_post = models.ImageField(upload_to='post_img/%Y/%m/%d', blank=True, null=True, verbose_name='Imagem')
    publicado_post = models.BooleanField(default=False, verbose_name='Publicado')


    def __str__(self):
        return self.titulo_post

categorias/views.py
from django.shortcuts import render

# Create your views here.

comentarios/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from .models import Post
from django.db.models import Q, Count, Case, When


class PostIndex(ListView):
    model = Post
    template_name = 'posts/index.html'
    paginate_by = 6
    context_object_name = 'posts'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.order_by('-id').filter(publicado_post=True)
        qs = qs.annotate(
            numero_comentarios=Count(
                Case(
                    When(comentario__publicado_comentario=True, then=1)
                )
            )
        )

        return qs

class PostBusca(PostIndex):
    pass


class PostCategoria(PostIndex):
    pass


class PostDetalhes(UpdateView):
    pass

posts/templates/posts/index.html
{% extends 'base.html' %}
{% load humanize %}


{% block conteudo %}
<!-- CONTENT -->
<div class="card-columns mt-4">
    
    {% for post in posts %}
    <div class="card">

       {% if post.imagem_post %}
        <a href="{% url 'post_detalhes' post.id %}">
            <img class="card-img-top"
                src="{{ post.imagem_post.url }}"
                alt="{{ post.titulo_post }}">
        </a>
        {% endif %}

        <div class="card-body">
            <h5 class="card-title">
                <a href="{% url 'post_detalhes' post.id %}">
                    {{ post.titulo_post }}
                </a>
            </h5>
            <p class="card-text">{{ post.excerto_post }}</p>
            <p class="card-text">
                <small class="text-muted">
                    {{ post.data_post|naturalday|title }} 
                    |
                    {{ post.comentario_set.count }} comentário(s)
                    |
                    {{ post.categoria_post }}</small>
            </p>

            <div class="text-right">
                <a href="{% url 'post_detalhes' post.id %}" class="btn btn-outline-secondary">Ler mais...</a>
            </div>
        </div>
    </div>
    {% endfor %}

</div>
<!--/CONTENT-->
{% include 'parciais/_pagination.html' %}
{% endblock %}

posts/templates/posts/post_categoria.html
{% extends 'base.html' %}
{% load humanize %}


{% block conteudo %}
<!-- CONTENT -->
<div class="card-columns mt-4">
    
    {% for post in posts %}
    <div class="card">

       {% if post.imagem_post %}
        <a href="{% url 'post_detalhes' post.id %}">
            <img class="card-img-top"
                src="{{ post.imagem_post.url }}"
                alt="{{ post.titulo_post }}">
        </a>
        {% endif %}

        <div class="card-body">
            <h5 class="card-title">
                <a href="{% url 'post_detalhes' post.id %}">
                    {{ post.titulo_post }}
                </a>
            </h5>
            <p class="card-text">{{ post.excerto_post }}</p>
            <p class="card-text">
                <small class="text-muted">
                    {{ post.data_post|naturalday|title }} 
                    |
                    {{ post.numero_comentarios }} comentário(s)
                    |
                    {{ post.categoria_post }}</small>
            </p>

            <div class="text-right">
                <a href="{% url 'post_detalhes' post.id %}" class="btn btn-outline-secondary">Ler mais...</a>
            </div>
        </div>
    </div>
    {% endfor %}

</div>
<!--/CONTENT-->
{% include 'parciais/_pagination.html' %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt">

<head>
    <title>Início em MyBlog</title>
    {% include 'parciais/_head.html' %}
</head>

<body>
{% include 'parciais/_nav.html' %}

<!-- Page Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            {% block conteudo %}{% endblock %}

        </div>
    </div>
</div>

{% include 'parciais/_footer.html' %}
</body>

</html>

templates/parciais/_footer.html
{% load static %}
<!--_footer.html-->
<footer class="bg-primary text-light">
    <div class="container navbar-dark pt-4 mt-5">
        <div class="row">
            <div class="col">
                <p class="text-left">Powered by Django</p>
            </div>
            <div class="col">
                <p class="text-right">Made By Phellipe Davyson</p>
            </div>
        </div>
    </div>
</footer>
<!--/_footer.html-->

<script src="{% static 'vendor/jquery/jquery.slim.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

templates/parciais/_head.html
{% load static %}
<!--_head.html-->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'vendor/bootstrap/css/theme_1564087106285.css' %}" rel="stylesheet">
<!--/_head.html-->

templates/parciais/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/parciais/_nav.html
<!--_nav.html-->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary static-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">MyBlog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'post_categoria' 'python' %}">Python</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'post_categoria' 'django' %}">Django</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'post_categoria' 'tecnologia' %}">Tecnologia</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'post_categoria' 'sistemas' %}">Sistemas</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0 ml-lg-4" action="{% url 'post_busca' %}">
                <input name="termo" value="{{ request.GET.termo }}" class="form-control mr-sm-2" type="search" placeholder="Pesquisar"
                       aria-label="Search">
            </form>
        </div>
    </div>
</nav>
<!--/_nav.html-->

templates/parciais/_pagination.html
{% if is_paginated %}
<div class="pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}
        <li class="page-item active">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endif %}